[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/SIS101.js"
healthcheckTimeout = 180

# La configuración de timezone debe estar en variables de entorno, no aquí
