[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

# La configuración de timezone debe estar en variables de entorno, no aquí
